### PR TITLE
add zenity backend

### PR DESCRIPTION
**Pull request by wheybags**
Hey, I'd like to use this and don't want to pull in all of gtk as a dependency, so I added a zenity backend, as you suggested in your readme.

### CODE REVIEW

**Comment by mlabbe** [comment]
This looks promising at a glance.  When I have some free time I'll give it a closer look.

Currently, simple_exec.h has a comment saying it was taken from another repo (one of yours).  By offering this PR, do you permanently and irrevocably agree to the code being licensed under the same license as the rest of NFD?

**Comment by wheybags** [comment]
Yup, sure. It is derived in part from an so post, there's another comment
with a link in it to that too.

**Comment by wheybags** [comment]
pushed a fix for trailing newlines in zenity output

**Comment by mlabbe** [comment]
Keep 'em coming.  I have yet to look at these changes (busy life), but I will holistically look at them all as soon as I can.

**Comment by wheybags** [comment]
bump :v (also fixed another stupid issue, surprising what you miss before you try really using something :p)

**Comment by wheybags** [comment]
Thanks!

**Comment by mlabbe** [comment]
Almost there!

I'm noticing the following warnings popping up when building in release_x64 config with gcc 5.4.0:

> 
> ../../src/simple_exec.h: In function ‘runCommandArray’:
> ../../src/simple_exec.h:99:13: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
>              write(errPipe[WRITE_FD], &err, 1);
>              ^
> ../../src/simple_exec.h:131:25: warning: ignoring return value of ‘read’, declared with attribute warn_unused_result [-Wunused-result]
>                          read(errPipe[READ_FD], &errChar, 1);
> 

We should check and correctly handle unexpected byte length reads.  Are you up for doing a small PR that fixes these new warnings to the devel branch?

**Comment by wheybags** [comment]
These calls are just a simple 1-char write and read to indicate if the process was successfully execed, not successfully run, it could have exited with nonzero exit status, but this checks whether the call to execv succeeded, ie, does the binary we asked to run exist and is it marked executable. If the exec was successful the process will never get to the write, because it will never return from the exec call.

If the write fails... well shit, ain't much we can do, and the process is about to exit. The read failing is the normal course. We read into errChar, which is initialised to zero. If the exec succeeds, nothing gets written to that pipe, the child runs, exits and the pipe is automatically closed. 
In this case, the read returns 0 bytes, and the destination buffer isn't modified, otherwise we write a 1 and that gets read. So, for the read, there's no need to use the return value.

I would happily make a pr to suppress the warnings though?

**Comment by mlabbe** [comment]
@wheybags Hello - this is the maintainer of Native FIle Dialogs.  The Zenity backend appears to have a discrepancy with the other backends.  Can you take a look at https://github.com/mlabbe/nativefiledialog/issues/95 and advise how to bring it in line with the other backends?  Thanks.

**Comment by wheybags** [comment]
Sorry, having looked at the man page for zenity, I don't think there is any way to do that unfortunately.

**Pull request merged**
