### PR TITLE
zenity dialog implementation

### PR DESCRIPTION
**Pull request by mgerhardy**
again no premake integration - but i've read in the readme that you would like to have something like this...

### CODE REVIEW

**Comment by mgerhardy** [comment]
could be extended to also support kdialog - but I don't have a kde env to test with.

**Comment by mgerhardy** [comment]
ups - forgot to implement --file-filter support - will leave that for someone else ;)

**Comment by onqtam** [comment]
will this get merged?

**Comment by mlabbe** [comment]
Indeed, while a Zenity implementation is desirable, it must be fully featured and easy to build.  This lib has hundreds of users and I want to make sure they don't fall into the trap of opting for a backend that doesn't meet the features described in the readme.

This PR needs work before it can be merged.  In addition to premake and --file-filter support, please see:
https://github.com/mlabbe/nativefiledialog/blob/master/docs/submitting_pull_requests.md

**Comment by mlabbe** [comment]
An alternative Zenity impl was merged to devel today which builds with Premake.  Took a look to see if it suits your needs!

**Pull request closed without merging**
